language: node_js
node_js:
  - "stable"
sudo: required
addons:
  chrome: stable
after_success: 
  - cp -R src docs/
  - ls docs
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
  repo: joymon/prayerbook
  target_branch: master
  keep-history: true