if: tag IS present OR commit_message != "Deploy joymon/prayerbook to github.com/joymon/prayerbook.git:master" OR tag = true
language: node_js
node_js:
  - "stable"
sudo: required
# require the branch name to be master (note for PRs this is the base branch name)

addons:
  chrome: stable
before_script:
  - echo ${TRAVIS_JOB_NUMBER}
  - npm version patch
  - npm run patch
  - npm run build
script:
  - npm test
  - npm run webdriver:update
  - npm run integrationTest
after_success: 
  - rm -rf docs
  - cp -R dist docs/
  - ls docs
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    on:
      branch: master
    repo: joymon/prayerbook
    target_branch: master
    keep-history: true
  - provider: pages
    local_dir: docs/
    skip_cleanup: true
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    on:
      tags: true
    repo: prayerbook/prayerbook.github.io
    target_branch: master
    keep-history: true
  
